# Generated by Django 4.0 on 2022-01-24 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddBug',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('bugname', models.CharField(max_length=255)),
                ('bugdate', models.CharField(max_length=13)),
                ('bugpriority', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
