# Generated by Django 4.0 on 2022-02-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddProject',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('projectname', models.CharField(max_length=255)),
                ('projectmanager', models.CharField(max_length=255)),
                ('timeStamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='addbug',
            name='projectname',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
