# Generated by Django 4.0 on 2022-02-22 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bts', '0002_addproject_addbug_projectname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addbug',
            name='projectname',
        ),
    ]
